
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\111111.PROGRAMOWANIE\AI W PYTHONIE\tkinter desinger projekts\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x600")
window.configure(bg = "#4B98E0")


canvas = Canvas(
    window,
    bg = "#4B98E0",
    height = 600,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    500.0,
    300.0,
    image=image_image_1
)

canvas.create_text(
    204.0,
    7.0,
    anchor="nw",
    text="ShiroAi-chan Control Panel",
    fill="#F9C6B3",
    font=("Inter Bold", 40 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=64.0,
    y=69.0,
    width=120.0,
    height=50.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=225.0,
    y=66.0,
    width=120.0,
    height=53.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    124.5,
    168.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFDDD3",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=53.0,
    y=151.0,
    width=143.0,
    height=32.0
)

canvas.create_text(
    31.0,
    119.0,
    anchor="nw",
    text="name:",
    fill="#FFFFFF",
    font=("Inter Regular", 24 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    810.0,
    312.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
